model_deployments:
  - name: mirodavide/vlm-vqa
    model_name: mirodavide/vlm-vqa
    tokenizer_name: mirodavide/vlm-vqa
    max_sequence_length: 20
    model_max_length: 20
    client_spec:
      class_name: "helm.clients.huggingface_client.HuggingFaceClient"
      args:
        pretrained_model_name_or_path: mirodavide/vlm-vqa