model_deployments:
  - name: mirodavide/vlm-vqa
    model_name: mirodavide/vlm-vqa
    tokenizer_name: mirodavide/vlm-vqa
    max_sequence_length: 321
    model_max_length: 321
    client_spec:
      class_name: "evaluation.helm.client.VLMClient"